[workspace]
members = [
  "src/nethint",
  "src/logging",
  "src/mapreduce",
  "src/allreduce",
  "src/rl",
  "src/litemsg",
  "src/replayer",
  "src/nhagent_v2",
  "src/nhagent",
  "src/utils",
  "src/rat_solver"
]

[profile.release]
debug = true
incremental = true
