[workspace]
members = ["src/nethint", "src/logging", "src/mapreduce", "src/allreduce", "src/rl", "src/litemsg", "src/replayer", "src/nhagent", "src/utils"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true
