# Specifiation of a Allreduce application experiment

# Number of jobs
ncases = 1

# Job size distributions [(percentage, number of workers)]
# job_size_distribution = [[40, 64], [40, 32]]
job_size_distribution = [[40, 64]]

# Images in a ML serving batch request, batch size = 64, each image has 3 channels, crop to 256x256
buffer_size = 12582912

# Number of iterations for all jobs
num_iterations = 1000

partially_sync = false

# Lambda of the poisson arrival, 12582912 * 8 / 50G * 1000 = 2s
poisson_lambda = 1_000_000_000.0

placement_strategy = { type = "Compact" }
# placement_strategy = { type = "CompactLoadBalanced" }
# placement_strategy = { type = "Spread" }
# placement_strategy = { type = "Random", args = 0 }

# global seed
seed = 1

# Output path of for the simulation results
directory = "/tmp/model_serving_result_for_paper/nonnegligible_computing_overhead"

# Number of repeats for each batch of experiments
batch_repeat = 1

[[batch]]
policy = "Random"
probe = { enable = false }
nethint_level = 2

# [[batch]]
# policy = "TopologyAware" # which is ring
# probe = { enable = true, round_ms = 100 }
# nethint_level = 1
# 
# [[batch]]
# policy = "TopologyAware" # which is ring
# probe = { enable = false }
# nethint_level = 1

[[batch]]
policy = "RAT"
probe = { enable = true, round_ms = 100 }
nethint_level = 2
# Auto tune after some iterations. default is disabled
auto_tune = 1000

[[batch]]
policy = "TopologyAware" # which is ring
probe = { enable = false }
nethint_level = 1

[[batch]]
policy = "RAT"
probe = { enable = false }
nethint_level = 2
# Auto tune after some iterations. default is disabled
auto_tune = 100

[simulator]
nethint = true
sample_interval_ns = 100_000_000 # 100ms
loopback_speed = 400
# possible values of fairness model are "PerFlowMaxMin", "PerVmPairMaxMin", and "TenantFlowMaxMin"
# fairness = "TenantFlowMaxMin"
fairness = "PerFlowMaxMin"

background_flow_hard = { enable = true, frequency_ns = 5_00_000_000, probability = 1.0, amplitude = 5, average_load = 0.1 }
# background_flow_hard = { enable = false }
# nethint_delay_ms = 100

[brain]
# Random seed for multiple uses
seed = 1
# Whether the cluster's bandwidth is asymmetric
asymmetric = false
# The percentage of nodes marked broken
broken = 0.0
# The slots of each physical machine
max_slots = 1
# how bandwidth is partitioned among multiple VMs in the same physical server, possible values are "RateLimited", "Guaranteed"
sharing_mode = "Guaranteed"
guaranteed_bandwidth = 25
background_flow_high_freq = { enable = true, probability = 1.0, amplitude = 10 }
# background_flow_high_freq = { enable = false }
gc_period = 10

# The topology for simulation
[brain.topology]
type = "Arbitrary"  # another possible value is "FatTree"

# [brain.topology.args] # When type = "FatTree"
# nports = 20           # the number of ports of a switch
# bandwidth = 100       # in Gbps
# oversub_ratio = 4.0   # oversubscription ratio

[brain.topology.args]         # When type = "Arbitrary"
nracks = 320        # the number of racks
rack_size = 6      # the number of hosts under a rack
host_bw = 100       # bandwidth of a host, in Gbps
rack_bw = 200       # bandwidth of a ToR switch, in Gbps

# [envs]
# KEY = "value"
