sample_interval_ns = 100_000_000 # 100ms

max_slots = 4

background_flow_hard = { enable = true, frequency_ns = 100_000_000_000, probability = 0.9, amplitude = 5 }

# The topology for simulation
[brain.topology]
type = "Arbitrary"  # another possible value is "FatTree"

# [brain.topology.args] # When type = "FatTree"
# nports = 20           # the number of ports of a switch
# bandwidth = 100       # in Gbps
# oversub_ratio = 4.0   # oversubscription ratio

[brain.topology.args]         # When type = "Arbitrary"
nracks = 2        # the number of racks
rack_size = 3      # the number of hosts under a rack
host_bw = 10       # bandwidth of a host, in Gbps
rack_bw = 10       # bandwidth of a ToR switch, in Gbps